name: template
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.0
  - black=23.1.0
  - flake8=6.0.0
  - isort=5.9.3
  - mypy=1.0.1
  - pre-commit=2.20.0
  - pytest=7.2.2
  - tox=4.3.5
